### PR TITLE
PEL:Description change in VPD SRCs

### PR DESCRIPTION
**Pull request by PriyangaRamasamy**
This commit modifies the description for VPD SRCs
BD554004 and BD554008.

Change-Id: I3587672afd7b47db362a3a905008f7de3e30c0ab

### CODE REVIEW

**Comment by PriyangaRamasamy** [comment]
Dependent openpower-vpd-parser commit https://github.com/ibm-openbmc/openpower-vpd-parser/pull/105  required to be merged along with this PR

**Comment by PriyangaRamasamy** [comment]
Fixes https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=481265

**Comment by spinler** [comment]
Are you putting this upstream too?

**Comment by PriyangaRamasamy** [comment]
> Are you putting this upstream too?

yes. in upstream its merged https://gerrit.openbmc.org/c/openbmc/phosphor-logging/+/60029

**Pull request merged**
