### PR TITLE
Reapply "openpower-pels: Move to libpldm pldm_transport APIs"

### PR DESCRIPTION
**Pull request by eddiejames**
This reverts commit eeb34e5670a4141230a93b310f474dcfd8a0f9e9.

### CODE REVIEW

**Comment by spinler** [comment]
jenkins run tests please

**Comment by spinler** [comment]
jenkins run tests please

**Comment by eddiejames** [comment]
jenkins run tests please

**Comment by spinler** [comment]
jenkins run tests please

**Review by spinler — APPROVED** [review]

**Pull request merged**
